# Various combinations of these filter criteria trigger various results
# The only one mandatory is world_id; empty arrays are ignored
uuid_msgs/UniqueID world_id
uuid_msgs/UniqueID[] ids  # Retrieved annotation uuid is within this list
string[] types            # Retrieved annotation type is within this list
string[] keywords         # Retrieved annotation has AT LEAST one of these keywords
string[] filter_by_some_other_constraint1   # TBD; ignored
string[] filter_by_some_other_constraint2   # TBD; ignored
string[] filter_by_some_other_constraint3   # TBD; ignored

uuid_msgs/UniqueID[] relationships   # TBD: need more thinking on this; ignored by now

----

# What went wrong, if anything
bool result
string message

Annotation[] annotations
