# Request saving currently published annotations, associated to the map identified by world_id.

# Unique ID of the associated map.
uuid_msgs/UniqueID world_id

---
# What went wrong, if anything
bool result
string message

Annotation[] annotations
AnnotationData[] data 