# Request saving currently published annotations, associated to the map identified by map_uuid.

# Unique ID of the associated map.
string map_uuid
uuid_msgs/UniqueID world_id


Annotation[] annotations
AnnotationData[] data 
---
# What went wrong, if anything
bool result
string message
