# Request saving currently published annotations, associated to the map identified by world_id.

# Unique ID of the associated map.
uuid_msgs/UniqueID world_id


Annotation[] annotations
AnnotationData[] data 
---
# What went wrong, if anything
bool result
string message
